/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockUniswapSol from "./MockUniswap.sol";
export type { mockUniswapSol };
import type * as versatilTokenSol from "./VersatilToken.sol";
export type { versatilTokenSol };
import type * as preusdcSol from "./preusdc.sol";
export type { preusdcSol };
export type { MockERC20 } from "./MockERC20";
export type { MockUniswapV3Pool } from "./MockUniswapV3Pool";
