/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockUniswapV3Pool,
  MockUniswapV3PoolInterface,
} from "../../contracts/MockUniswapV3Pool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint160",
        name: "_sqrtPriceX96",
        type: "uint160",
      },
      {
        internalType: "address",
        name: "_token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token1",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "slot0",
    outputs: [
      {
        internalType: "uint160",
        name: "",
        type: "uint160",
      },
      {
        internalType: "int24",
        name: "",
        type: "int24",
      },
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "sqrtPriceX96",
    outputs: [
      {
        internalType: "uint160",
        name: "",
        type: "uint160",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0_",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1_",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50604051610230380380610230833981016040819052602c916084565b600080546001600160a01b039485166001600160a01b03199182161790915560018054938516938216939093179092556002805491909316911617905560ca565b6001600160a01b0381168114608157600080fd5b50565b600080600060608486031215609857600080fd5b835160a181606d565b602085015190935060b081606d565b604085015190925060bf81606d565b809150509250925092565b610157806100d96000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c80630dfe1681146100675780631aab09bd146100915780633850c7bd146100a45780638db791d2146100ea578063c6312e10146100fd578063d21220a714610110575b600080fd5b6001546001600160a01b03165b6040516001600160a01b0390911681526020015b60405180910390f35b600154610074906001600160a01b031681565b60008054604080516001600160a01b039092168252602082018390528101829052606081018290526080810182905260a0810191909152600160c082015260e001610088565b600054610074906001600160a01b031681565b600254610074906001600160a01b031681565b6002546001600160a01b031661007456fea26469706673582212200779745109e91428e71d091c0fbf4f498a75aea7fd8134b8296d1e1c3c8d5a3d64736f6c634300081c0033";

type MockUniswapV3PoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockUniswapV3PoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockUniswapV3Pool__factory extends ContractFactory {
  constructor(...args: MockUniswapV3PoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _sqrtPriceX96: BigNumberish,
    _token0: AddressLike,
    _token1: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _sqrtPriceX96,
      _token0,
      _token1,
      overrides || {}
    );
  }
  override deploy(
    _sqrtPriceX96: BigNumberish,
    _token0: AddressLike,
    _token1: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _sqrtPriceX96,
      _token0,
      _token1,
      overrides || {}
    ) as Promise<
      MockUniswapV3Pool & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockUniswapV3Pool__factory {
    return super.connect(runner) as MockUniswapV3Pool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockUniswapV3PoolInterface {
    return new Interface(_abi) as MockUniswapV3PoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockUniswapV3Pool {
    return new Contract(address, _abi, runner) as unknown as MockUniswapV3Pool;
  }
}
