/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockQuoter,
  MockQuoterInterface,
} from "../../../contracts/MockUniswap.sol/MockQuoter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_rate",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ethToUsdcRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint160",
        name: "",
        type: "uint160",
      },
    ],
    name: "quoteExactInputSingle",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506040516101f63803806101f6833981016040819052602c916033565b600055604b565b600060208284031215604457600080fd5b5051919050565b61019c8061005a6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063625ed5031461003b578063f7729d4314610056575b600080fd5b61004460005481565b60405190815260200160405180910390f35b6100446100643660046100a9565b6000670de0b6b3a76400006000548461007d9190610119565b6100879190610144565b9695505050505050565b6001600160a01b03811681146100a657600080fd5b50565b600080600080600060a086880312156100c157600080fd5b85356100cc81610091565b945060208601356100dc81610091565b9350604086013562ffffff811681146100f457600080fd5b925060608601359150608086013561010b81610091565b809150509295509295909350565b808202811582820484141761013e57634e487b7160e01b600052601160045260246000fd5b92915050565b60008261016157634e487b7160e01b600052601260045260246000fd5b50049056fea2646970667358221220eff0d242389c97d571c592d5bc058d9a39ec9c12b51a174a3c8cca1bb02541e064736f6c634300081c0033";

type MockQuoterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockQuoterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockQuoter__factory extends ContractFactory {
  constructor(...args: MockQuoterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _rate: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_rate, overrides || {});
  }
  override deploy(
    _rate: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_rate, overrides || {}) as Promise<
      MockQuoter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockQuoter__factory {
    return super.connect(runner) as MockQuoter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockQuoterInterface {
    return new Interface(_abi) as MockQuoterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockQuoter {
    return new Contract(address, _abi, runner) as unknown as MockQuoter;
  }
}
